version: '3'

vars:

  # we can pass these values dynamically...while executing
  # eg: task build:jar:lhs VERSION=1.0.2

  VERSION: "1.0.0"
  GRADLEW: '{{if eq OS "windows"}}gradlew.bat{{else}}./gradlew{{end}}'
  SLEEP_CMD: '{{if eq OS "windows"}}timeout{{else}}sleep{{end}}'
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yaml"
  APPS_DC_FILE: "{{.DC_DIR}}/apps.yaml"
  MONITORING_DC_FILE: "{{.DC_DIR}}/monitoring.yaml"


tasks:
  default:
    cmds:
      - "echo 'Hello From Taskfile' "
      - "echo '{{OS}}' "
      - "echo '{{.GRADLEW}}' "

########################################### Format ################################################

  format:
    cmds:
      - "{{.GRADLEW}} spotlessApplyAll"

  format:check:
    cmds:
      - "{{.GRADLEW}} spotlessCheckAll"


########################################### Build Docker Images ################################################


  build:images:
    cmds:
#      - "{{.GRADLEW}} bootBuildImage -x test -PBUILD_SOURCEVERSION={{.VERSION}}"  # we don't need for all apps
      - task: build:image:lhs
      - task: build:image:css
      - task: build:image:lps

  build:image:lhs:
    cmds:
      - "{{.GRADLEW}} :loan-hub-service:bootBuildImage -x test -PBUILD_SOURCEVERSION={{.VERSION}}"

  build:image:css:
    cmds:
      - "{{.GRADLEW}} :credit-score-service:bootBuildImage -x test -PBUILD_SOURCEVERSION={{.VERSION}}"

  build:image:lps:
    cmds:
      - "{{.GRADLEW}} :loan-process-service:bootBuildImage -x test -PBUILD_SOURCEVERSION={{.VERSION}}"


##################################### Build Jars ############################################


  build:jars:
    cmds:
      - task: build:jar:lhs
      - task: build:jar:css
      - task: build:jar:lps


  build:jar:lhs: # lhs = loan-hub-service
    cmds:
      - "{{.GRADLEW}} :loan-hub-service:bootJar -PBUILD_SOURCEVERSION={{.VERSION}}"

  build:jar:css: # cs = credit-score-service
    cmds:
      - "{{.GRADLEW}} :credit-score-service:bootJar -PBUILD_SOURCEVERSION={{.VERSION}}"

  build:jar:lps: # lps = loan-process-service
    cmds:
      - "{{.GRADLEW}} :loan-process-service:bootJar -PBUILD_SOURCEVERSION={{.VERSION}}"


  clean:
    cmds:
      - "{{.GRADLEW}} clean"   # cleans build folder ( includes jars )


########################################## Build ############################################

  build:
    cmds:
      - "{{.GRADLEW}} build"  # this runs all build tasks ( tests, bootJar, etc )

  build:x-test:
    cmds:
      - "{{.GRADLEW}} build -x test"

  build:fresh:
    cmds:
      - "{{.GRADLEW}} build --refresh-dependencies -x test"


########################################### Infrastructure ############################################

  start:infra:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} up -d"

  stop:infra:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} down"

  restart:infra:
    cmds:
      - task: stop:infra
      - task: sleep
      - task: start:infra

  start:infra:all:
    cmds:
      - "docker compose --profile ui -f {{.INFRA_DC_FILE}} up -d"

  stop:infra:all:
    cmds:
      - "docker compose --profile ui -f {{.INFRA_DC_FILE}} down"

  restart:infra:all:
    cmds:
      - task: stop:infra:all
      - task: sleep
      - task: start:infra:all


########################################### Apps Containers ############################################

  start:apps:
    cmds:
      - "docker compose -f {{.APPS_DC_FILE}} up -d"

  start:apps:fresh:
    deps: [build:images]
    cmds:
      - "docker compose -f {{.APPS_DC_FILE}} up -d"

  stop:apps:
    cmds:
      - "docker compose -f {{.APPS_DC_FILE}} down"


  start:
    cmds:
      - task: start:infra
      - task: sleep
        vars:
          DURATION: 5
      - task: start:apps
      - "echo 'Applications are ready' "

  start:fresh:
    cmds:
      - task: start:infra
      - task: sleep
        vars:
          DURATION: 7
      - task: start:apps:fresh
      - "echo 'Applications are ready' "

  stop:
    cmds:
      - task: stop:apps
      - task: stop:infra
      - "echo 'Applications are stopped' "

  ################################ Monitoring ############################################


  start:monitoring:
    cmds:
      - "docker compose -f {{.MONITORING_DC_FILE}} up -d"

  stop:monitoring:
    cmds:
      - "docker compose -f {{.MONITORING_DC_FILE}} down"

  restart:monitoring:
    cmds:
      - task: stop:monitoring
      - task: sleep
        vars:
          DURATION: 7
      - task: start:monitoring



################################ Running Jars ############################################


  # to run jars tmux is required ( install tmux )
  start:jars:
    deps: [build:jars]
    cmds:
      - task: start:jar:lhs
      - task: start:jar:css
      - task: start:jar:lps
      - "echo 'Applications are ready' "

  stop:jars:
    cmds:
      - task: stop:jar:lhs
      - task: stop:jar:css
      - task: stop:jar:lps
      - "echo 'Applications are stopped' "

  start:jar:lhs:  # lhs = loan-hub-service
    cmds:
      - "tmux new -s loan-hub-service -d 'java -jar loan-hub-service/build/libs/loan-hub-service-{{.VERSION}}.jar'"

  stop:jar:lhs:
    cmds:
      - "tmux kill-session -t loan-hub-service"

  start:jar:css:  # cs = credit-score-service
    cmds:
      - "tmux new -s credit-score-service -d 'java -jar credit-score-service/build/libs/credit-score-service-{{.VERSION}}.jar'"

  stop:jar:css:
    cmds:
      - "tmux kill-session -t credit-score-service"

  start:jar:lps: # lps = loan-process-service
    cmds:
      - "tmux new -s loan-process-service -d 'java -jar loan-process-service/build/libs/loan-process-service-{{.VERSION}}.jar'"

  stop:jar:lps:
    cmds:
      - "tmux kill-session -t loan-process-service"

########################################## Utilities ############################################

  # to run from cmd: task sleep DURATION=10
  sleep:
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - "{{.SLEEP_CMD}} {{.DURATION}}"

