name: 'insta-cred'
services:
  loan-hub-postgres:
    image: postgres:17-alpine
    container_name: loan-hub-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m


  loan-hub-redis:
    image: redis/redis-stack-server:7.2.0-v13-x86_64
    container_name: loan-hub-redis
    ports:
      - "16379:6379"
    environment:
      REDIS_USERNAME: "redis"
      REDIS_PASSWORD: "redis"
    volumes:
      - ./redis:/redis
    command: [ "sh", "/redis/start.sh" ]

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 5


  loan-hub-redis-ui:
    profiles:
      - ui
    image: redis/redisinsight:latest
    container_name: loan-hub-redis-ui
    ports:
      - "15540:5540"
    healthcheck:
      test: [ "CMD", "echo", "Hello" ]
      interval: 30s
      timeout: 10s
      retries: 5