name: 'insta-cred'
services:
  loan-hub-postgres:
    image: postgres:17-alpine
    container_name: loan-hub-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m


  loan-hub-redis:
    image: redis/redis-stack-server:7.2.0-v13-x86_64
    container_name: loan-hub-redis
    ports:
      - "16379:6379"
    environment:
      REDIS_USERNAME: "redis"
      REDIS_PASSWORD: "redis"
    volumes:
      - ./redis:/redis
    command: [ "sh", "/redis/start.sh" ]

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 5


  loan-hub-redis-ui:
    profiles:
      - ui
    image: redis/redisinsight:latest
    container_name: loan-hub-redis-ui
    ports:
      - "5540:5540"
    healthcheck:
      test: [ "CMD", "echo", "Hello" ]
      interval: 30s
      timeout: 10s
      retries: 5


  credit-score-mongodb:
    image: mongodb/mongodb-community-server:7.0.7-ubi9
    container_name: credit-score-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      AUTH: "enabled"
    volumes:
      - ./mongodb/init-script.js:/docker-entrypoint-initdb.d/init-script.js
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh",  "--eval", "db.adminCommand('ping').ok", "--quiet" ]
      interval: 30s
      timeout: 10s
      retries: 5


  insta-cred-rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    container_name: insta-cred-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m