name: 'insta-cred'
services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: "--config.file=/etc/prometheus/prometheus.yaml"

  promtail:
    image: grafana/promtail:main-732cc8b
    container_name: promtail
    volumes:
      - ./promtail/promtail-docker-config.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--config.file=/etc/promtail/docker-config.yaml"

  loki:
    image: grafana/loki:main-732cc8b
    container_name: loki
    command: "-config.file=/etc/loki/local-config.yaml"
    ports:
      - "3100:3100"
    depends_on:
      - promtail

  tempo:
    image: grafana/tempo:main-e3c2848
    container_name: tempo
    command: "-config.file /etc/tempo-config.yaml"
    ports:
      - "3200:3200"     # Tempo
      - "9411:9411"     # Zipkin
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo-config.yaml

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  grafana_data: {}
