server:
  port: ${SERVER_PORT:8082}

loan-process:
  loan-requests-exchange: loan.requests.exchange
  new-loan-requests-queue: new.loan.requests.queue
  approved-loan-requests-routing-key: approved.loan.requests.key
  # this key ( approved.loan.requests.key ) will match with approved.loan.requests.#
  # note wile publishing we shouldn't use wild cards
  # for the approved.loan.requests.# routing key...there are two listeners ( 1. Loan hub,  2. Credit Score )
  rejected-loan-requests-routing-key: rejected.loan.requests.key
  # this key ( rejected.loan.requests.key ) will match with rejected.loan.requests.#


spring:
  application.name: loan-process-service
  ############################### Database ############################

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  #  jpa.show-sql: true

  # ref: https://contribute.liquibase.com/extensions-integrations/directory/integration-docs/springboot/configuration/
  liquibase:
    change-log: classpath:/db/migrations/changelog_master.xml
  #   rollback-file: rollback.sql


  ############################## Rabbit MQ ############################

  rabbitmq:
    enabled: true
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}



################## Management ############################
management:
  endpoints:
    web.exposure.include: '*'
    health.show-details: always
  info.git.mode: full
  metrics.tags.application: ${spring.application.name}
  tracing:
    enabled: false # enable dynamically using env variable
#    zapkin.tracing.endpoint: http://localhost:9411  # pass this dynamically
    sampling.probability: 1


################################# Logging ############################

logging.level:
  org.springframework.web: DEBUG
  io.lettuce: DEBUG
#    liquibase: DEBUG