server:
  port: ${SERVER_PORT:8081}

credit-score:
  loan-requests-exchange: loan.requests.exchange
  approved-loan-requests-queue: approved.loan.requests.queue.1
  approved-loan-requests-routing-key: approved.loan.requests.#

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:insta-cred}
      username: ${MONGODB_USERNAME:mongo}
      password: ${MONGODB_PASSWORD:mongo}


  ############################## Rabbit MQ ############################

  rabbitmq:
    enabled: true
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}

################# mongock config ###################
mongock:
  runner-type: initializingbean
  migration-scan-package:
    - com.paravar.instacred.creditScore.data.migrations

################## Management ############################
management:
  endpoints:
    web.exposure.include: '*'
    health.show-details: always
    prometheus.enabled: true
  info.git.mode: full
  metrics.tags.application: ${spring.application.name}
  tracing:
    enable: true
    sampling.probability: 1