server:
    port: ${APP_PORT:8080}

loan-hub:
    page-size: 10
spring:
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 16379
      password: redis
      username: redis

      cache-null-values: false
      key-prefix: loan-hub-cache
      #      time-to-live: 60000
      use-key-prefix: true
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      ssl:
        enabled: false

############################### Database ############################

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

#  jpa.show-sql: true

  # ref: https://contribute.liquibase.com/extensions-integrations/directory/integration-docs/springboot/configuration/
  liquibase:
    change-log: classpath:/db/migrations/changelog_master.xml
#    rollback-file: rollback.sql

############################## Management ############################

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always


################################# Logging ############################

logging.level:
    org.springframework.web: DEBUG
    io.lettuce: DEBUG
#    liquibase: DEBUG