server:
    port: ${APP_PORT:8080}

loan-hub:
    page-size: 10
    max-page-size: 100

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

#  jpa.show-sql: true

  # ref: https://contribute.liquibase.com/extensions-integrations/directory/integration-docs/springboot/configuration/
  liquibase:
    change-log: classpath:/db/migrations/changelog_master.xml
#    rollback-file: rollback.sql

#logging.level.liquibase: DEBUG

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
